name: Deploy Architecture to Primary Region

on:
  push:
    branches:
      - main 
    paths:
      - 'iac/**'  
  workflow_dispatch:

permissions:
  contents: read  
  id-token: write  

jobs:
  deploy-architecture:
    uses: ./.github/workflows/deploy-architecture-common.yml
    with:
      parametersFile: 'iac/main.parameters.primary.json'
      location: 'centralus'
      applicationName: 'BuildASecureWebSolution'
      environment: 'dev'
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}