name: Deploy to Primary Region

on:
  push:
    branches:
    - main  # Trigger deployment on push to the main branch
    paths:
    - 'iac/**'  # Only trigger if the 'iac' folder is changed
  workflow_dispatch:

permissions:
  contents: read  # Read repository content (necessary for checkout)
  id-token: write  # Write ID token to authenticate with federated credentials

jobs:
  call-common:
    uses: ./.github/workflows/deploy-architecture.yml
    with:
      parametersFile: 'iac/main.parameters.primary.json'
        location: 'centralus'
        applicationName: 'BuildASecureWebSolution'
        environment: 'dev'
      secrets:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
