name: Deploy Regional architecture

on:
  workflow_call:
    inputs:
      parametersFile:
        required: true
        type: string
      location:
        required: true
        type: string
      applicationName:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true

permissions:
  contents: read  # Read repository content (necessary for checkout)
  id-token: write  # Write ID token to authenticate with federated credentials

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deployment
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: ${{inputs.applicationName}}-${{ inputs.location }}-${{inputs.environment}}-${{ github.run_id }}
          location: ${{ inputs.location }}
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: iac/main.bicep
          parameters-file: ${{ inputs.parametersFile }}
